export const UPDATETHEME = "UPDATETHEME";
export const UPDATEFULLSCREENSTATUS = "UPDATEFULLSCREENSTATUS";
export const SETUSERNAME = "SETUSERNAME";
export const SETMENUCOLLAPSED = "SETMENUCOLLAPSED";
